version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: twitter-db
    volumes:
      - volume-postgresql:/var/lib/postgresql

volumes:
  volume-postgresql:
    external: true
